easy_admin:

  site_name: Arthur, The Bald One
  
  design:
        menu:

              - { route: 'accueil', label: "Quitter l'admin", icon: 'home' }
              - { entity: 'Oeuvre', label: 'Oeuvre', icon: 'map-marker' }
              - { entity: 'Exposition', label: 'Exposition', icon: 'comments' }

  entities:
        - App\Entity\Oeuvre
        - App\Entity\Exposition
        
      # List the entity class name you want to manage
#         - App\Entity\Product
#         - App\Entity\Category
#         - App\Entity\User
